name: run-tests
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-oas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: spectral linter (OpenAPI ruleset)
        run: bunx @stoplight/spectral-cli lint -r ./config/.spectral.yaml ./specs/oh-dear.openapi.yaml --format github-actions

      - name: vacuum linter (recommended ruleset)
        run: |
          curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh
          vacuum -r ./config/vacuum.yaml lint ./specs/oh-dear.openapi.yaml --no-banner --pipeline-output

  lint-arazzo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: redocly linter (arazzo)
        run: bunx @redocly/cli lint ./specs/oh-dear.arazzo.yaml --format github-actions
